name: unit-test
on:
  push:
    branches:
      - main
      - dev

jobs:
  hardhat-test:
    runs-on: ubuntu-latest
    name: Hardhat unit test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: cd backend && npm install
      - name: Create local network & deploy contracts
        shell: bash
        run: cd backend && npx hardhat node && npx hardhat run scripts/deploy.js --network localhost
      - name: Test
        run: cd backend && npx hardhat test

  slither-audit:
    runs-on: ubuntu-latest
    name: Slither
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Slither
        shell: bash
        run: cd backend && npx slither .
