name: unit-test
on:
  push:
    branches:
      - main
      - dev

jobs:
  hardhat-test:
    runs-on: ubuntu-latest
    name: Hardhat unit test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: cd backend && npm install
      - name: Test
        run: cd backend && npx hardhat test --network hardhat

  slither-audit:
    runs-on: ubuntu-latest
    name: Slither
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: cd backend && npm install && python3 -m pip install slither-analyzer
      - name: Slither
        shell: bash
        run: cd backend && slither .
